// <auto-generated />
using System;
using BookingSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409092658_update-validation")]
    partial class updatevalidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            AppointmentDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ahmed Hassan",
                            Phone = "01012345678",
                            Service = "Haircut"
                        },
                        new
                        {
                            BookingId = 2,
                            AppointmentDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Sara Ali",
                            Phone = "01198765432",
                            Service = "Massage"
                        },
                        new
                        {
                            BookingId = 3,
                            AppointmentDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Mohamed Tarek",
                            Phone = "01234567890",
                            Service = "Dental Checkup"
                        },
                        new
                        {
                            BookingId = 4,
                            AppointmentDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Nour Ibrahim",
                            Phone = "01555555555",
                            Service = "Facial"
                        },
                        new
                        {
                            BookingId = 5,
                            AppointmentDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Omar Khaled",
                            Phone = "01099998888",
                            Service = "Gym Session"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
